geonode.layers.api.exceptions
=============================

.. py:module:: geonode.layers.api.exceptions


Classes
-------

.. autoapisummary::

   geonode.layers.api.exceptions.GeneralDatasetException
   geonode.layers.api.exceptions.InvalidDatasetException
   geonode.layers.api.exceptions.InvalidMetadataException
   geonode.layers.api.exceptions.MissingMetadataException


Module Contents
---------------

.. py:class:: GeneralDatasetException

   Bases: :py:obj:`rest_framework.exceptions.APIException`


   .. py:attribute:: status_code
      :value: 500



   .. py:attribute:: default_detail
      :value: 'Error during dataset replace.'



   .. py:attribute:: default_code
      :value: 'dataset_exception'



   .. py:attribute:: category
      :value: 'dataset_api'



.. py:class:: InvalidDatasetException

   Bases: :py:obj:`rest_framework.exceptions.APIException`


   .. py:attribute:: status_code
      :value: 500



   .. py:attribute:: default_detail
      :value: 'Input payload is not valid'



   .. py:attribute:: default_code
      :value: 'invalid_dataset_exception'



   .. py:attribute:: category
      :value: 'dataset_api'



.. py:class:: InvalidMetadataException

   Bases: :py:obj:`rest_framework.exceptions.APIException`


   .. py:attribute:: status_code
      :value: 500



   .. py:attribute:: default_detail
      :value: 'Input payload is not valid'



   .. py:attribute:: default_code
      :value: 'invalid_metadata_exception'



   .. py:attribute:: category
      :value: 'dataset_api'



.. py:class:: MissingMetadataException

   Bases: :py:obj:`rest_framework.exceptions.APIException`


   .. py:attribute:: status_code
      :value: 400



   .. py:attribute:: default_detail
      :value: 'Metadata is missing'



   .. py:attribute:: default_code
      :value: 'missing_metadata_exception'



   .. py:attribute:: category
      :value: 'dataset_api'



