geonode.maps.api.exception
==========================

.. py:module:: geonode.maps.api.exception


Classes
-------

.. autoapisummary::

   geonode.maps.api.exception.GeneralMapsException


Module Contents
---------------

.. py:class:: GeneralMapsException

   Bases: :py:obj:`rest_framework.exceptions.APIException`


   .. py:attribute:: status_code
      :value: 500



   .. py:attribute:: default_detail
      :value: 'Error during maps operation'



   .. py:attribute:: default_code
      :value: 'maps_exception'



   .. py:attribute:: category
      :value: 'maps_api'



